### ISSUE TITLE
How to get rid of Posts in index

### ISSUE THREAD

**Issue by starsareintherose** [syui/hugo-theme-arch#11]
https://syui.cf/hugo-theme-arch/

Just like this, posts still shown in the website, how to get ride of i?

**Comment by starsareintherose** [comment]
and also seems the RSS button doesn't link to the XML file

**Comment by syui** [comment]
Set the baseurl in `config.toml` appropriately.

**Comment by starsareintherose** [comment]
Could you give me an example for rss and ignore posts

**Comment by syui** [comment]
now fix rss

**Comment by syui** [comment]
`_posts/`, `contens/`

index.md, _index.md

**Comment by starsareintherose** [comment]
Sorry I can't get it. Do you mean config with replacing `post = "/:year/:month/:day/:slug" ` ? Or just mv files in content/ ? But if I mv file out of content/post, it won't be shown in the index

**Comment by syui** [comment]
If you want to delete examples of posts, delete all files from _posts/, contens/.

**Comment by syui** [comment]
See here for submission rules.
https://gohugo.io/content-management/organization/

**Comment by starsareintherose** [comment]
Right, maybe I describe not clearly, see the example site and https://bioarchlinux.org/ from https://github.com/BioArchLinux/HomePage

You can see, even we haven't configured a md called posts, it would present in the index, 

![image](https://user-images.githubusercontent.com/37733075/168056631-aa756667-63ef-47a4-8d1b-3f1b0fe92250.png)
![image](https://user-images.githubusercontent.com/37733075/168056709-a7cd1e09-d415-4992-9f7e-f2a853ac2f82.png)

**Comment by starsareintherose** [comment]
It always presents in the second position in the index maybe.

**Comment by syui** [comment]
ok, it is controlled by `layouts/partials/article_list.html`.

**Comment by starsareintherose** [comment]
so, it seems that it auto generated and consider post as a page, what methods would we do to rm it?

**Comment by syui** [comment]
ok, example committed.

**Comment by syui** [comment]
Thank you for writing this issue.

**Comment by syui** [comment]
exmaple :

```html
{{ $s := path.Dir (.Permalink | relURL) }}
{{ $t := index (split $s "/") 5 }}
{{ if $t }}

write here

{{ end }}
```

**Comment by syui** [comment]
There may be a better way. If so, we look forward to your pull req.

**Comment by starsareintherose** [comment]
it seems for me, it's totually blank page

**Comment by starsareintherose** [comment]
https://bioarchlinux.org/

**Comment by syui** [comment]
Probably when there is nothing to get with `index (split $s "/") 5`.
If not sub-domain, you may need to set it to 4.

**Comment by starsareintherose** [comment]
right, thanks.
