### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Derson5** [syui/hugo-theme-arch#2]
Hi,

Is there any chance to little change table view? I make table with centered text. In your theme, horizontal text is centered, but not vertically, and the first column heading string touches the second column. It`s look like this ![arch](http://i67.tinypic.com/2ip2f5.png)

And I wanted to be like this (like in Hyde theme)
![hyde](http://i67.tinypic.com/33a6te1.png)

**Comment by syui** [comment]
@Derson5 

```css
th, td {
    text-align: center;
}
```

**Comment by Derson5** [comment]
Big thanks!
