### ISSUE TITLE
when i start this i get a 404

### ISSUE THREAD

**Issue by richbreton** [syui/hugo-theme-arch#4]
I have to go to  http://localhost:1313/hugo-theme-arch/ to see anything

if I just go to  http://localhost:1313 like your instructions say I get a 404.

I have tried starting it with just hugo server and  hugo server --theme=hugo-theme-arch --buildDrafts 

both have the same results.

How can I make this the site root?

**Comment by syui** [comment]
@richbreton 

> config.toml

```
- baseurl = "https://syui.github.io/hugo-theme-arch/"
+ baseurl = "/"
```
