### ISSUE TITLE
If I want to change the logo

### ISSUE THREAD

**Issue by starsareintherose** [syui/hugo-theme-arch#8]
Hello,
If I want to change the ArchLinux logo to other logos, what documents should I change?

**Comment by syui** [comment]
change

> hugo-theme-arch/themes/hugo-theme-arch/layouts/partials/title.htmll

```html
<span class="icon-archlinux"></span>
```

**Comment by starsareintherose** [comment]
but how the image stored

**Comment by syui** [comment]
icomoon

**Comment by starsareintherose** [comment]
okay, thanks, how to change the color?

**Comment by syui** [comment]
css

```css
span.icon-archlinux{
color:#000;
}
```

**Comment by starsareintherose** [comment]
okay, thanks

**Comment by starsareintherose** [comment]
but if I don't check it is blue not 000

**Comment by syui** [comment]
ref : hugo-theme-arch/themes/hugo-theme-arch/static/css/font.css

color code : https://htmlcolorcodes.com/

**Comment by syui** [comment]
change color : a:hover

**Comment by starsareintherose** [comment]
thanks, it solved
